#!/bin/bash
#Bullseye

./compile.sh  BOARD=odroidn2 BRANCH=current RELEASE=bullseye BUILD_MINIMAL=no BUILD_DESKTOP=no REPOSITORY_INSTALL=u-boot,kernel,armbian-config,armbian-firmware USE_CCACHE=yes INSTALL_HEADERS=yes KERNEL_CONFIGURE=no SKIP_BOOTSPLASH=yes COMPRESS_OUTPUTIMAGE=img
./compile.sh  BOARD=odroidxu4 BRANCH=current RELEASE=bullseye BUILD_MINIMAL=no BUILD_DESKTOP=no REPOSITORY_INSTALL=u-boot,kernel,armbian-config,armbian-firmware USE_CCACHE=yes INSTALL_HEADERS=yes KERNEL_CONFIGURE=no SKIP_BOOTSPLASH=yes COMPRESS_OUTPUTIMAGE=img
./compile.sh  BOARD=orangepi3 BRANCH=current RELEASE=bullseye BUILD_MINIMAL=no BUILD_DESKTOP=no REPOSITORY_INSTALL=u-boot,kernel,armbian-config,armbian-firmware USE_CCACHE=yes INSTALL_HEADERS=yes KERNEL_CONFIGURE=no SKIP_BOOTSPLASH=yes COMPRESS_OUTPUTIMAGE=img
./compile.sh  BOARD=orangepione BRANCH=current RELEASE=bullseye BUILD_MINIMAL=no BUILD_DESKTOP=no REPOSITORY_INSTALL=u-boot,kernel,armbian-config,armbian-firmware USE_CCACHE=yes INSTALL_HEADERS=yes KERNEL_CONFIGURE=no SKIP_BOOTSPLASH=yes COMPRESS_OUTPUTIMAGE=img
./compile.sh  BOARD=orangepioneplus BRANCH=current RELEASE=bullseye BUILD_MINIMAL=no BUILD_DESKTOP=no REPOSITORY_INSTALL=u-boot,kernel,armbian-config,armbian-firmware USE_CCACHE=yes INSTALL_HEADERS=yes KERNEL_CONFIGURE=no SKIP_BOOTSPLASH=yes COMPRESS_OUTPUTIMAGE=img
./compile.sh  BOARD=orangepiprime BRANCH=current RELEASE=bullseye BUILD_MINIMAL=no BUILD_DESKTOP=no REPOSITORY_INSTALL=u-boot,kernel,armbian-config,armbian-firmware USE_CCACHE=yes INSTALL_HEADERS=yes KERNEL_CONFIGURE=no SKIP_BOOTSPLASH=yes COMPRESS_OUTPUTIMAGE=img
./compile.sh  BOARD=orangepizero BRANCH=current RELEASE=bullseye BUILD_MINIMAL=no BUILD_DESKTOP=no REPOSITORY_INSTALL=u-boot,kernel,armbian-config,armbian-firmware USE_CCACHE=yes INSTALL_HEADERS=yes KERNEL_CONFIGURE=no SKIP_BOOTSPLASH=yes COMPRESS_OUTPUTIMAGE=img
./compile.sh  BOARD=tinkerboard BRANCH=current RELEASE=bullseye BUILD_MINIMAL=no BUILD_DESKTOP=no REPOSITORY_INSTALL=u-boot,kernel,armbian-config,armbian-firmware USE_CCACHE=yes INSTALL_HEADERS=yes KERNEL_CONFIGURE=no SKIP_BOOTSPLASH=yes COMPRESS_OUTPUTIMAGE=img
./compile.sh  BOARD=odroidc2 BRANCH=current RELEASE=bullseye BUILD_MINIMAL=no BUILD_DESKTOP=no REPOSITORY_INSTALL=u-boot,kernel,armbian-config,armbian-firmware USE_CCACHE=yes INSTALL_HEADERS=yes KERNEL_CONFIGURE=no SKIP_BOOTSPLASH=yes COMPRESS_OUTPUTIMAGE=img
./compile.sh  BOARD=orangepipc2 BRANCH=current RELEASE=bullseye BUILD_MINIMAL=no BUILD_DESKTOP=no REPOSITORY_INSTALL=u-boot,kernel,armbian-config,armbian-firmware USE_CCACHE=yes INSTALL_HEADERS=yes KERNEL_CONFIGURE=no SKIP_BOOTSPLASH=yes COMPRESS_OUTPUTIMAGE=img
./compile.sh  BOARD=orangepipc BRANCH=current RELEASE=bullseye BUILD_MINIMAL=no BUILD_DESKTOP=no REPOSITORY_INSTALL=u-boot,kernel,armbian-config,armbian-firmware USE_CCACHE=yes INSTALL_HEADERS=yes KERNEL_CONFIGURE=no SKIP_BOOTSPLASH=yes COMPRESS_OUTPUTIMAGE=img
./compile.sh  BOARD=orangepiplus BRANCH=current RELEASE=bullseye BUILD_MINIMAL=no BUILD_DESKTOP=no REPOSITORY_INSTALL=u-boot,kernel,armbian-config,armbian-firmware USE_CCACHE=yes INSTALL_HEADERS=yes KERNEL_CONFIGURE=no SKIP_BOOTSPLASH=yes COMPRESS_OUTPUTIMAGE=img
./compile.sh  BOARD=orangepiwin BRANCH=current RELEASE=bullseye BUILD_MINIMAL=no BUILD_DESKTOP=no REPOSITORY_INSTALL=u-boot,kernel,armbian-config,armbian-firmware USE_CCACHE=yes INSTALL_HEADERS=yes KERNEL_CONFIGURE=no SKIP_BOOTSPLASH=yes COMPRESS_OUTPUTIMAGE=img
./compile.sh  BOARD=orangepizeroplus2-h5 BRANCH=current RELEASE=bullseye BUILD_MINIMAL=no BUILD_DESKTOP=no REPOSITORY_INSTALL=u-boot,kernel,armbian-config,armbian-firmware USE_CCACHE=yes INSTALL_HEADERS=yes KERNEL_CONFIGURE=no SKIP_BOOTSPLASH=yes COMPRESS_OUTPUTIMAGE=img

#Sid

#./compile.sh  BOARD=odroidn2 BRANCH=current RELEASE=sid BUILD_MINIMAL=no BUILD_DESKTOP=no REPOSITORY_INSTALL=u-boot,kernel,armbian-config,armbian-firmware USE_CCACHE=yes INSTALL_HEADERS=yes KERNEL_CONFIGURE=no SKIP_BOOTSPLASH=yes COMPRESS_OUTPUTIMAGE=img
#./compile.sh  BOARD=odroidxu4 BRANCH=current RELEASE=sid BUILD_MINIMAL=no BUILD_DESKTOP=no REPOSITORY_INSTALL=u-boot,kernel,armbian-config,armbian-firmware USE_CCACHE=yes INSTALL_HEADERS=yes KERNEL_CONFIGURE=no SKIP_BOOTSPLASH=yes COMPRESS_OUTPUTIMAGE=img
#./compile.sh  BOARD=orangepi3 BRANCH=current RELEASE=sid BUILD_MINIMAL=no BUILD_DESKTOP=no REPOSITORY_INSTALL=u-boot,kernel,armbian-config,armbian-firmware USE_CCACHE=yes INSTALL_HEADERS=yes KERNEL_CONFIGURE=no SKIP_BOOTSPLASH=yes COMPRESS_OUTPUTIMAGE=img
#./compile.sh  BOARD=orangepione BRANCH=current RELEASE=sid BUILD_MINIMAL=no BUILD_DESKTOP=no REPOSITORY_INSTALL=u-boot,kernel,armbian-config,armbian-firmware USE_CCACHE=yes INSTALL_HEADERS=yes KERNEL_CONFIGURE=no SKIP_BOOTSPLASH=yes COMPRESS_OUTPUTIMAGE=img
#./compile.sh  BOARD=orangepioneplus BRANCH=current RELEASE=sid BUILD_MINIMAL=no BUILD_DESKTOP=no REPOSITORY_INSTALL=u-boot,kernel,armbian-config,armbian-firmware USE_CCACHE=yes INSTALL_HEADERS=yes KERNEL_CONFIGURE=no SKIP_BOOTSPLASH=yes COMPRESS_OUTPUTIMAGE=img
#./compile.sh  BOARD=orangepiprime BRANCH=current RELEASE=sid BUILD_MINIMAL=no BUILD_DESKTOP=no REPOSITORY_INSTALL=u-boot,kernel,armbian-config,armbian-firmware USE_CCACHE=yes INSTALL_HEADERS=yes KERNEL_CONFIGURE=no SKIP_BOOTSPLASH=yes COMPRESS_OUTPUTIMAGE=img
#./compile.sh  BOARD=orangepizero BRANCH=current RELEASE=sid BUILD_MINIMAL=no BUILD_DESKTOP=no REPOSITORY_INSTALL=u-boot,kernel,armbian-config,armbian-firmware USE_CCACHE=yes INSTALL_HEADERS=yes KERNEL_CONFIGURE=no SKIP_BOOTSPLASH=yes COMPRESS_OUTPUTIMAGE=img
#./compile.sh  BOARD=tinkerboard BRANCH=current RELEASE=sid BUILD_MINIMAL=no BUILD_DESKTOP=no REPOSITORY_INSTALL=u-boot,kernel,armbian-config,armbian-firmware USE_CCACHE=yes INSTALL_HEADERS=yes KERNEL_CONFIGURE=no SKIP_BOOTSPLASH=yes COMPRESS_OUTPUTIMAGE=img
#./compile.sh  BOARD=odroidc2 BRANCH=current RELEASE=sid BUILD_MINIMAL=no BUILD_DESKTOP=no REPOSITORY_INSTALL=u-boot,kernel,armbian-config,armbian-firmware USE_CCACHE=yes INSTALL_HEADERS=yes KERNEL_CONFIGURE=no SKIP_BOOTSPLASH=yes COMPRESS_OUTPUTIMAGE=img
#./compile.sh  BOARD=orangepipc2 BRANCH=current RELEASE=sid BUILD_MINIMAL=no BUILD_DESKTOP=no REPOSITORY_INSTALL=u-boot,kernel,armbian-config,armbian-firmware USE_CCACHE=yes INSTALL_HEADERS=yes KERNEL_CONFIGURE=no SKIP_BOOTSPLASH=yes COMPRESS_OUTPUTIMAGE=img
#./compile.sh  BOARD=orangepipc BRANCH=current RELEASE=sid BUILD_MINIMAL=no BUILD_DESKTOP=no REPOSITORY_INSTALL=u-boot,kernel,armbian-config,armbian-firmware USE_CCACHE=yes INSTALL_HEADERS=yes KERNEL_CONFIGURE=no SKIP_BOOTSPLASH=yes COMPRESS_OUTPUTIMAGE=img
#./compile.sh  BOARD=orangepiplus BRANCH=current RELEASE=sid BUILD_MINIMAL=no BUILD_DESKTOP=no REPOSITORY_INSTALL=u-boot,kernel,armbian-config,armbian-firmware USE_CCACHE=yes INSTALL_HEADERS=yes KERNEL_CONFIGURE=no SKIP_BOOTSPLASH=yes COMPRESS_OUTPUTIMAGE=img
#./compile.sh  BOARD=orangepiwin BRANCH=current RELEASE=sid BUILD_MINIMAL=no BUILD_DESKTOP=no REPOSITORY_INSTALL=u-boot,kernel,armbian-config,armbian-firmware USE_CCACHE=yes INSTALL_HEADERS=yes KERNEL_CONFIGURE=no SKIP_BOOTSPLASH=yes COMPRESS_OUTPUTIMAGE=img
#./compile.sh  BOARD=orangepizeroplus2-h5 BRANCH=current RELEASE=sid BUILD_MINIMAL=no BUILD_DESKTOP=no REPOSITORY_INSTALL=u-boot,kernel,armbian-config,armbian-firmware USE_CCACHE=yes INSTALL_HEADERS=yes KERNEL_CONFIGURE=no SKIP_BOOTSPLASH=yes COMPRESS_OUTPUTIMAGE=img
#./compile.sh  BOARD=uefi-x86 BRANCH=current RELEASE=sid BUILD_MINIMAL=no BUILD_DESKTOP=no REPOSITORY_INSTALL=u-boot,kernel,armbian-config,armbian-firmware USE_CCACHE=yes INSTALL_HEADERS=yes KERNEL_CONFIGURE=no SKIP_BOOTSPLASH=yes COMPRESS_OUTPUTIMAGE=img

